<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vishnus-MacBook-Air.local" failures="1" tests="3" name="iOS" time="136.783" errors="0" timestamp="2021-12-31T14:46:17 IST">
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="27.541"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserName" time="38.492">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.__test]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.__test]
at com.qa.tests.LoginTests.invalidUserName(LoginTests.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="38.637"/>
</testsuite> <!-- iOS -->
